 思路 ：从文件 批量获取n个文件

由于WRF输出数据的特殊性，需要先从day20文件中挑选出第二天的预测数据，如果缺失，则为nan
于是可以得到一个文件列表
从文件列表 分小批量读取nc数据
根据时间戳

In [1]:
import numpy as np
import arrow

def datetime2datestr(date_struct, datestr_format):
    if isinstance(datestr_format, str):
        datestr_format = list([datestr_format])

    if not isinstance(date_struct, list):
        date_struct = list([date_struct])

    datestr_list = np.empty(shape=[len(date_struct), len(datestr_format)]).tolist()
    k = 0
    for i_date in date_struct:
        datestr_temp = []
        for i_format in datestr_format:
            datestr = i_date.format(i_format)
            datestr_temp.append(datestr)
        datestr_list[k][:] = datestr_temp
        k = k + 1
    return np.squeeze(datestr_list)
def gen_time_list(span_unit, datetime_beg, datetime_end, datestr_format='YYYY-MM-DD HH:mm:ss'):
    # span_unit: 'hour', 'day' ...

    if isinstance(datetime_beg, str):
        datetime_beg = arrow.get(datetime_beg, datestr_format)

    if isinstance(datetime_end, str):
        datetime_end = arrow.get(datetime_end, datestr_format)

    time_list = []
    for tt in arrow.Arrow.range(span_unit, datetime_beg, datetime_end):
        time_list.append(tt)
    return time_list


In [2]:
PATH='E:'
#WRF_DIR_TEMPLATE='/public/home/pathop/wrffc/data/wrf/%s/%s/%s20/WTHR_2D_%s' 
WRF_DIR_TEMPLATE=PATH+'\\%s\\%s\\%s20\\WTHR_2D_%s.nc' 
#WTHR_2D_DIR_TEMPLATE = PATH + '\\%s\\%s\\%s20\\'
#print(WTHR_2D_DIR_TEMPLATE)

In [3]:
zone='d02'  # just  note
datetime_beg= '2019-01-04 01:00:00'
fcst_datetime_end='2019-05-01 00:00:00'
datetime_end='2019-05-01 00:00:00'
datestr_format='YYYY-MM-DD HH:mm:ss'
if isinstance(datetime_end, str):
        datetime_end = arrow.get(datetime_end, datestr_format)
WRF_DATA=True               
if WRF_DATA:
        WRF_date_struct_list = gen_time_list('hour', datetime_beg, fcst_datetime_end)  #generate time list by arrow like :<Arrow [2019-01-28T08:00:00+00:00]>
        WRF_flnm_list = []
        import arrow
        import os
        for i_hour in WRF_date_struct_list:
            #print(i_hour)
            WRF_datestr_file = datetime2datestr(i_hour,'YYYYMMDDHH')#    目标文件的时间戳格式'YYYYMMDDHH' YYYY-MM-DD_HH:mm:ss
            has_file = 0
            for i in range(2, 2 * 8): # 找前后的day 目录
                if i_hour.float_timestamp > datetime_end.float_timestamp:
                    WRF_datestr_dir = datetime2datestr(datetime_end.shift(days=-i), ['YYYY', 'YYYYMM', 'YYYYMMDD'])
                else:
                    WRF_datestr_dir = datetime2datestr(i_hour.shift(days=-i), ['YYYY', 'YYYYMM', 'YYYYMMDD'])
                WRF_datestr_flnm = WRF_datestr_dir.tolist() + [WRF_datestr_file.tolist()]
                #print(met_datestr_flnm)
                WRF_flnm = WRF_DIR_TEMPLATE % tuple(WRF_datestr_flnm)  # 
                #print(WRF_flnm)
                if os.path.exists(WRF_flnm):
                    WRF_flnm_list.append(WRF_flnm)
                    has_file = 1
                    print('exist this file: %s' %WRF_flnm)
                    break
            if not has_file:
                print('although file %s does not eixt ,it also be add to file name list' %WRF_flnm)
                WRF_flnm_list.append(WRF_flnm)
                pass

exist this file: E:\2019\201901\2019010220\WTHR_2D_2019010401.nc
exist this file: E:\2019\201901\2019010220\WTHR_2D_2019010402.nc
exist this file: E:\2019\201901\2019010220\WTHR_2D_2019010403.nc
exist this file: E:\2019\201901\2019010220\WTHR_2D_2019010404.nc
exist this file: E:\2019\201901\2019010220\WTHR_2D_2019010405.nc
exist this file: E:\2019\201901\2019010220\WTHR_2D_2019010406.nc
exist this file: E:\2019\201901\2019010220\WTHR_2D_2019010407.nc
exist this file: E:\2019\201901\2019010220\WTHR_2D_2019010408.nc
exist this file: E:\2019\201901\2019010220\WTHR_2D_2019010409.nc
exist this file: E:\2019\201901\2019010220\WTHR_2D_2019010410.nc
exist this file: E:\2019\201901\2019010220\WTHR_2D_2019010411.nc
exist this file: E:\2019\201901\2019010220\WTHR_2D_2019010412.nc
exist this file: E:\2019\201901\2019010220\WTHR_2D_2019010413.nc
exist this file: E:\2019\201901\2019010220\WTHR_2D_2019010414.nc
exist this file: E:\2019\201901\2019010220\WTHR_2D_2019010415.nc
exist this file: E:\2019\

exist this file: E:\2019\201901\2019012420\WTHR_2D_2019020121.nc
exist this file: E:\2019\201901\2019012520\WTHR_2D_2019020122.nc
exist this file: E:\2019\201901\2019012620\WTHR_2D_2019020123.nc
exist this file: E:\2019\201901\2019013120\WTHR_2D_2019020200.nc
exist this file: E:\2019\201901\2019013120\WTHR_2D_2019020201.nc
exist this file: E:\2019\201901\2019013120\WTHR_2D_2019020202.nc
exist this file: E:\2019\201901\2019013120\WTHR_2D_2019020203.nc
exist this file: E:\2019\201901\2019013120\WTHR_2D_2019020204.nc
exist this file: E:\2019\201901\2019013120\WTHR_2D_2019020205.nc
exist this file: E:\2019\201901\2019013120\WTHR_2D_2019020206.nc
exist this file: E:\2019\201901\2019013120\WTHR_2D_2019020207.nc
exist this file: E:\2019\201901\2019013120\WTHR_2D_2019020208.nc
exist this file: E:\2019\201901\2019013120\WTHR_2D_2019020209.nc
exist this file: E:\2019\201901\2019013120\WTHR_2D_2019020210.nc
exist this file: E:\2019\201901\2019013120\WTHR_2D_2019020211.nc
exist this file: E:\2019\

exist this file: E:\2019\201903\2019032520\WTHR_2D_2019032715.nc
exist this file: E:\2019\201903\2019032520\WTHR_2D_2019032716.nc
exist this file: E:\2019\201903\2019032520\WTHR_2D_2019032717.nc
exist this file: E:\2019\201903\2019032520\WTHR_2D_2019032718.nc
exist this file: E:\2019\201903\2019032520\WTHR_2D_2019032719.nc
exist this file: E:\2019\201903\2019032520\WTHR_2D_2019032720.nc
exist this file: E:\2019\201903\2019032520\WTHR_2D_2019032721.nc
exist this file: E:\2019\201903\2019032520\WTHR_2D_2019032722.nc
exist this file: E:\2019\201903\2019032520\WTHR_2D_2019032723.nc
exist this file: E:\2019\201903\2019032620\WTHR_2D_2019032800.nc
exist this file: E:\2019\201903\2019032620\WTHR_2D_2019032801.nc
exist this file: E:\2019\201903\2019032620\WTHR_2D_2019032802.nc
exist this file: E:\2019\201903\2019032620\WTHR_2D_2019032803.nc
exist this file: E:\2019\201903\2019032620\WTHR_2D_2019032804.nc
exist this file: E:\2019\201903\2019032620\WTHR_2D_2019032805.nc
exist this file: E:\2019\

exist this file: E:\2019\201904\2019042720\WTHR_2D_2019042908.nc
exist this file: E:\2019\201904\2019042720\WTHR_2D_2019042909.nc
exist this file: E:\2019\201904\2019042720\WTHR_2D_2019042910.nc
exist this file: E:\2019\201904\2019042720\WTHR_2D_2019042911.nc
exist this file: E:\2019\201904\2019042720\WTHR_2D_2019042912.nc
exist this file: E:\2019\201904\2019042720\WTHR_2D_2019042913.nc
exist this file: E:\2019\201904\2019042720\WTHR_2D_2019042914.nc
exist this file: E:\2019\201904\2019042720\WTHR_2D_2019042915.nc
exist this file: E:\2019\201904\2019042720\WTHR_2D_2019042916.nc
exist this file: E:\2019\201904\2019042720\WTHR_2D_2019042917.nc
exist this file: E:\2019\201904\2019042720\WTHR_2D_2019042918.nc
exist this file: E:\2019\201904\2019042720\WTHR_2D_2019042919.nc
exist this file: E:\2019\201904\2019042720\WTHR_2D_2019042920.nc
exist this file: E:\2019\201904\2019042720\WTHR_2D_2019042921.nc
exist this file: E:\2019\201904\2019042720\WTHR_2D_2019042922.nc
exist this file: E:\2019\

In [4]:
WRF_flnm_list[4].endswith('2019042520.nc')

False

In [5]:
def find_file_by_time(filetime,file_list):
    q=[]
    for each_file in file_list:
        #print(each_file)
        if str(each_file).endswith(filetime):
            #print(each_file)
            q.append(each_file)
        else:
            pass
            
    return q
file_name=find_file_by_time('2019042520.nc',WRF_flnm_list)
file_name[0]       

'E:\\2019\\201904\\2019042320\\WTHR_2D_2019042520.nc'

In [6]:
#WRF_flnm_list
#得到了文件列表
import pandas as  pd
from datetime import datetime
from math import sqrt
from numpy import concatenate
from matplotlib import pyplot
from pandas import read_csv
from pandas import DataFrame
import time
flnm_aqi='C:\\Users\\lining\\Desktop\\myjob\\My_WRF\\changsha_one_hot_aqi.csv'
#aqi = pd.read_csv(flnm_aqi,dtype='str').set_index(['time'])
#aqi.loc['2018-01-01 00:00:00':'2018-01-01 05:00:00']
#aqi.loc[['2018-01-01 00:00:00','2018-01-01 05:00:00']]  # 获取不连续的多个

In [7]:
def stack_2dxa_to3d_np(ds,features3d_stack=[],features2d_stack=['SW','PBLH']):
    imgs3d=[]
    import numpy as np
    for each in features3d_stack:
        each_2d=ds3[each][dict(pressure=1)].values
        imgs3d.append(each_2d)
    for each in features2d_stack:
        each_2d=ds[each].values
        imgs3d.append(each_2d)
    np3d=np.asarray(imgs3d,np.float32)
    
    return np3d

In [24]:
def generate_arrays_labels_from_file(datetime_beg,datetime_end,nc_flnm_list,flnm_target,batch_size=2 ,shuffle =False):
    import arrow
    import xarray
    import numpy as np
    XY_date_struct_list = gen_time_list('hour', datetime_beg, datetime_end) 
    Y_date_list=[]
    X_date_list=[]
    for each in XY_date_struct_list:
        Y_date_list.append(each.format('YYYY-MM-DD HH:mm:ss'))
        X_date_list.append(each.shift(years=1).format('YYYYMMDDHH')) # nc数据加上一年，后面一定要改
########################################################################
    nc_flnm_full_list=[]
    for each in X_date_list:
        #print('each',each)
        nc_flnm_full_list.append(find_file_by_time(each+'.nc',nc_flnm_list))
    #print(nc_flnm_full_list)
############################################################################       
    try:
        aqi=pd.read_csv(flnm_target,dtype='str').set_index(['time'])
    except FileNotFoundError :
        print('%s does not exist. \n' % flnm_aqi)
###########################################################################
    if shuffle:
        time_indices=list(range(len(XY_date_struct_list)))
        np.random.shuffle(time_indices)
    for start_idx in range(0,len(XY_date_struct_list) - batch_size+1,batch_size):
        if shuffle:
            excerpt=time_indices[start_idx:start_idx + batch_size]
            time_batch=[]
            nc_fullflnm_batch=[]
            nc_data_batch=[]
            y_batch=[]
            for i in excerpt:
                #print('i',i)
                time_batch.append(Y_date_list[i])
                #ds = xarray.open_dataset(nc_flnm_full_list[i][0])
                nc_fullflnm_batch.append(nc_flnm_full_list[i][0])
                #print('choose file_nc',nc_flnm_full_list[i][0])
                #nc_data_batch.append(xarray.open_dataset(nc_flnm_full_list[i][0]))
                #y_batch.append(Y_fl_list[i])
           # for each in nc_fullflnm_batch:
                #print('each nc',each)
                #nc_data_batch.append(xarray.open_dataset(each))
                
        else:
            time_indices=list(range(len(XY_date_struct_list)))
            excerpt =time_indices[start_idx:start_idx + batch_size]# slice
            time_batch=[]
            nc_fullflnm_batch=[]
            nc_data_batch=[]
            y_batch=[]
            for i in excerpt:
                time_batch.append(Y_date_list[i])
                nc_fullflnm_batch.append(nc_flnm_full_list[i][0])
        #x_batch=X_fl_list[excerpt] 
        #y_batch=Y_fl_list[excerpt]
    #print(time_batch)
    #print(X_date_list)
    for each in nc_fullflnm_batch:
        print('each nc',each)
        ds=xarray.open_dataset(each)
        np3d=stack_2dxa_to3d_np(ds,features3d_stack=[],features2d_stack=['TA_1000hPa','TA_800hPa','PBLH'])
        nc_data_batch.append(np3d)
    return aqi.loc[time_batch],nc_fullflnm_batch,nc_data_batch

In [26]:
datetime_beg= '2018-01-27 01:00:00'
fcst_datetime_end='2018-04-26 00:00:00'
datetime_end='2018-05-01 00:00:00'
datestr_format='YYYY-MM-DD HH:mm:ss'
dir_name_X='E:\\'
nc_flnm_list=WRF_flnm_list;
flnm_target='C:\\Users\\lining\\Desktop\\myjob\\My_WRF\\changsha_one_hot_aqi.csv'
a,b,c=generate_arrays_labels_from_file(datetime_beg,datetime_end,nc_flnm_list,flnm_target,batch_size=2,shuffle =False)

each nc E:\2019\201904\2019042820\WTHR_2D_2019043023.nc
each nc E:\2019\201904\2019042920\WTHR_2D_2019050100.nc


In [29]:
a

1st  2nd  3rd  4th  5th  6th
time                                             
2018-04-30 23:00:00  1.0  0.0  0.0  0.0  0.0  0.0
2018-05-01 00:00:00  1.0  0.0  0.0  0.0  0.0  0.0

In [27]:
c#c#c[1].values

[array([[[ 26.846527  ,  27.515106  ,  28.071106  , ...,  26.847273  ,
           26.833487  ,  26.82016   ],
         [ 26.987274  ,  27.62207   ,  28.104584  , ...,  26.818396  ,
           26.812397  ,  26.805798  ],
         [ 27.474945  ,  27.892334  ,  28.207825  , ...,  26.785809  ,
           26.787794  ,  26.788082  ],
         ...,
         [  0.8470154 ,   1.9641113 ,   2.983673  , ...,  20.51867   ,
           20.294512  ,  19.969185  ],
         [  0.9086304 ,   2.1661682 ,   3.1354675 , ...,  20.482851  ,
           20.264559  ,  19.938643  ],
         [  0.97784424,   2.033142  ,   2.831726  , ...,  20.483776  ,
           20.249031  ,  19.918528  ]],
 
        [[ 21.329393  ,  21.233582  ,  21.151972  , ...,  18.053568  ,
           18.043118  ,  18.025389  ],
         [ 21.325174  ,  21.16204   ,  21.043514  , ...,  18.00549   ,
           18.002258  ,  17.998413  ],
         [ 21.278004  ,  21.116547  ,  20.93887   , ...,  17.95074   ,
           17.969246  ,  17.9721

In [28]:
b

['E:\\2019\\201904\\2019042820\\WTHR_2D_2019043023.nc',
 'E:\\2019\\201904\\2019042920\\WTHR_2D_2019050100.nc']

In [88]:
import xarray
ds1=xarray.open_dataset(b[0])
ds2=xarray.open_dataset(b[1])
ds['TA_1000hPa']

<xarray.DataArray 'TA_1000hPa' (south_north: 162, west_east: 162)>
array([[19.670105, 19.997528, 20.391907, ..., 22.241743, 22.329393, 22.393467],
       [19.360046, 19.9516  , 20.470245, ..., 22.169205, 22.265247, 22.327974],
       [19.301788, 19.88742 , 20.467407, ..., 22.097134, 22.188368, 22.256851],
       ...,
       [-6.150543, -5.413116, -4.672607, ...,  4.533409,  4.5251  ,  4.522429],
       [-6.015717, -5.282043, -4.545746, ...,  4.497761,  4.490406,  4.489476],
       [-5.943573, -5.253387, -4.824219, ...,  4.463865,  4.461855,  4.458569]],
      dtype=float32)
Coordinates:
    XLONG    (south_north, west_east) float32 ...
    XLAT     (south_north, west_east) float32 ...
    XTIME    datetime64[ns] ...
    Time     datetime64[ns] ...
Dimensions without coordinates: south_north, west_east
Attributes:
    vert_interp_type:  pressure

In [161]:
def flielist_iter_list(X_fl_list, Y_fl_list, batch_size=2 ,shuffle =True):
    import numpy as np
    assert len(X_fl_list)==len(Y_fl_list)
    num_samples = len(X_fl_list)
    
    if shuffle:
        indices =list(range(len(X_fl_list)))
        np.random.shuffle(indices)
    for start_idx in range(0,len(X_fl_list) - batch_size+1,batch_size):
        if shuffle:
            excerpt=indices[start_idx:start_idx + batch_size]
            x_batch=[]
            y_batch=[]
            for i in excerpt:
                x_batch.append(X_fl_list[i])
                y_batch.append(Y_fl_list[i])
        
        else :
            excerpt = slice(start_idx,start_idx + batch_size)
            x_batch=X_fl_list[excerpt] 
            y_batch=Y_fl_list[excerpt]
    
        yield x_batch, y_batch

In [2]:
def flielist_iter_np(X_fl_list, Y_fl_list, X_input_np,Target_np ,batch_size=2 ,shuffle =True):
    '''
    X_fl_list=['a.nc','b.nc','c.nc','d.nc','e.nc','f.nc','g.nc','h.nc']
    Y_fl_list=['1.nc','2.nc','3.nc','4.nc','5.nc','6.nc','7.nc','8.nc']
    X_input_np=np.ones((len(X_fl_list),6,5))  # 三维
    Target_np=np.arange(len(X_fl_list))

    for a, b ,c ,d in  flielist_iter(X_fl_list, Y_fl_list,X_input_np,Target_np, batch_size =2 ,shuffle =True):
    print('X_input',a)
    print('Y_input',b)
    print('X_input',c)
    print('Target',d)
    
    '''
    
    import numpy as np
    assert len(X_fl_list)==len(Y_fl_list)
    num_samples = len(X_fl_list)
    
    if shuffle:
        indices =list(range(len(X_fl_list)))
        np.random.shuffle(indices)
    for start_idx in range(0,len(X_fl_list) - batch_size+1,batch_size):
        if shuffle:
            excerpt=indices[start_idx:start_idx + batch_size]
            x_batch=[]
            y_batch=[]
            x_input_batch=[]
            target_batch=[]
            for i in excerpt:
                x_batch.append(X_fl_list[i])
                y_batch.append(Y_fl_list[i])
                target_batch.append(Target_np[i])
                x_input_batch.append(X_input_np[i])
        
        else :
            excerpt = slice(start_idx,start_idx + batch_size)
            x_batch=X_fl_list[excerpt] 
            y_batch=Y_fl_list[excerpt]
            target_batch=Target_np[excerpt]
        x_input_batch=np.asarray(x_input_batch)    
        target_batch=np.asarray(target_batch)
        yield x_batch, y_batch,x_input_batch,target_batch

In [3]:
#小批量batch 文件
#https://www.cnblogs.com/q735613050/p/8367173.html

In [4]:
import numpy as np
X_fl_list=['a.nc','b.nc','c.nc','d.nc','e.nc','f.nc','g.nc','h.nc']
Y_fl_list=['1.nc','2.nc','3.nc','4.nc','5.nc','6.nc','7.nc','8.nc']
#X_input_np=np.random.randn((len(X_fl_list),6,5,8))  # 三维 ones
X_input_np=np.ones((len(X_fl_list),6,5,8))
Target_np=np.arange(len(X_fl_list))

for a, b ,c ,d in  flielist_iter_np(X_fl_list, Y_fl_list,X_input_np,Target_np, batch_size =2 ,shuffle =True):
    print('X_input',a)
    print('Y_input',b)
    print('X_input',c)
    print('Target',d)

X_input ['d.nc', 'g.nc']
Y_input ['4.nc', '7.nc']
X_input [[[[1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]


In [121]:
for a, b  in  flielist_iter_list(X_fl_list, Y_fl_list, batch_size =4 ,shuffle =False):
    print('X_input',a)
    print('Y_input',b)
    

X_input ['a.nc', 'b.nc', 'c.nc', 'd.nc']
Y_input ['1.nc', '2.nc', '3.nc', '4.nc']
X_input ['e.nc', 'f.nc', 'g.nc', 'h.nc']
Y_input ['5.nc', '6.nc', '7.nc', '8.nc']


In [6]:
import numpy as np
idx=list(range(8))
print(idx)
print(np.random.shuffle(idx))
print(idx)

[0, 1, 2, 3, 4, 5, 6, 7]
None
[6, 4, 1, 2, 5, 7, 3, 0]


In [7]:
list(idx[5:7])

[7, 3]

In [8]:
#原文：https://blog.csdn.net/zwqjoy/article/details/88356094 
def generate_arrays_from_file(path, batch_size):
    while 1:
        f = open(path)
        cnt = 0
        X = []
        Y = []
        for line in f:
            # create Numpy arrays of input data
            # and labels, from each line in the file
            x, y = process_line(line)
            X.append(x)
            Y.append(y)
            cnt += 1
            if cnt == batch_size:
                cnt = 0
                yield (np.array(X), np.array(Y))
                X = []
                Y = []
        f.close()

In [9]:
def generate_np3d_from_Xarray(path, batch_size):
    '''每个小时一个样本（3d）
     每个批次生成 batch_size 个 样本'''
    while 1:
        f = open(path)
        cnt = 0
        X = []
        Y = []
        for line in f:
            # create Numpy arrays of input data
            # and labels, from each line in the file
            x, y = process_line(line)
            X.append(x)
            Y.append(y)
            cnt += 1
            if cnt == batch_size:
                cnt = 0
                yield (np.array(X), np.array(Y))
                X = []
                Y = []
        f.close()